Card post
artemka81/dream-team pull request #10
Opened 2018-02-09 14:00 UTC by alina-antonova-web

Card-post ready

2018-02-09 20:11 UTC, artemka81 requested changes
Задание выполнено хорошо, но не perfex pixel (когда верстка совпадает с макетов в .psd)
Для проверки точности добавь себе в Chrome это расширение https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=ru

2018-02-09 20:11 UTC, artemka81 commented on app/scss/cards.scss
> +	margin: 5%;
Margin у картинки не соответствует margin у заголовка и кнопки карточек.

2018-02-09 20:11 UTC, artemka81 commented on app/scss/cards.scss
> +.card {
— Отталкивание элементов всегда делай от верхнего к нижнему (используя magrin-bottom)
— Для того что бы у картинки, заголовка и кнопки были одинаковые отступы лучше было применить padding к .card, чем потом подгонять разный margin у потомков

2018-02-10 09:58 UTC, alina-antonova-web commented
@artemka81 проверяй

2018-02-10 10:05 UTC, merged